# dsh-client-ui-forkspace — fork of @deepseek-ai/dsh-client-ui-workspace
# (0.1.2-rc.1) adding a fork-tree view to the grouped sidebar browser.
#
# WHY this package BUILDS FROM SOURCE while every sibling ships a prebuilt
# lib/: the fork's whole point is that it is a build unit outside the upstream
# monorepo, so lib/ is an artifact of the build, not an input. A bare checkout
# contains only committed *.d.ts — no lib/types JS and no guarantee the
# committed lib/client.js matches the sources. This derivation regenerates the
# bundle instead of trusting the committed one.
#
# TWO-STEP BUILD, ORDER IS LOAD-BEARING:
#   1. `build:types` = tsc -p tsconfig.types.json --noEmitOnError
#   2. `tsdown --config-loader unrun`
# tsdown consumes lib/types/index.js, which does not exist in a bare checkout.
# Running tsdown alone fails with `[UNRESOLVED_ENTRY] Cannot resolve entry
# module lib/types/index.js`. package.json already chains both correctly in
# its `bundle` script, so the derivation runs that script rather than
# re-listing the steps in shell (single source of truth for the order).
# --noEmitOnError is what makes a type error FAIL the build rather than emit
# past it.
#
# ---------------------------------------------------------------------------
# THE MISSING-LOCKFILE PROBLEM
# ---------------------------------------------------------------------------
# The fork commits NO package-lock.json, and Nix's npm tooling is lock-keyed
# (buildNpmPackage -> fetchNpmDeps keys the npmDeps FOD off
# $src/package-lock.json), so nothing could be pinned as-is.
#
# vendor/package-lock.json is that build lock. It is NOT hand-written and is
# NOT the repo's vendor.package-lock.json (that is the old dep-less
# mkNpmPlugin lock for the previous same-name vendor-override package).
# Provenance: generated by `npm install --legacy-peer-deps` on a clean
# checkout of d45b71d, and confirmed byte-stable across three independent
# installs (this one, /tmp/lockcheck, /tmp/verify-planA-FINAL2) — all md5
# 245203cc41464f8aec0f3e6329ccddc4, 131042 bytes, lockfileVersion 3, 228
# `packages` entries. Portability checked: all 227 `resolved` URLs are on
# registry.npmjs.org (no git/file/workspace links), zero entries with a
# `link`, and zero occurrences of any absolute host path. So it resolves
# inside the sandbox unchanged.
#
# npmDepsHash below is the REAL hash of THAT file, produced by
# prefetch-npm-deps (not guessed, not read off a fakeHash failure) and
# reproduced identically on repeat runs.
#
# ---------------------------------------------------------------------------
# --legacy-peer-deps IS MANDATORY, INCLUDING AT `npm ci` TIME
# ---------------------------------------------------------------------------
# Plain npm 10.9.8 crashes in arborist (`Cannot read properties of null`) on
# tsdown's optional peer @vitejs/devtools-vitest. The flag is not just a
# lock-generation quirk: `npm ci` against this lock WITHOUT the flag fails
# hard with `Missing: argparse@2.0.1 from lock file`, and succeeds WITH it
# (199 packages). nixpkgs' npmConfigHook error text recommends this exact
# flag. So it is set as npmFlags (which reaches both `npm ci` and
# `npm rebuild`) rather than npmInstallFlags alone.
#
# ---------------------------------------------------------------------------
# SOURCE PINNING
# ---------------------------------------------------------------------------
# Reviewed commit 4weaver/dsh-client-ui-workspace@d45b71d, pinned by rev so the
# derivation never tracks a moving branch. (An earlier revision of this file
# vendored a local tarball because the commit was unpushed; that blob is gone
# now that the rev is reachable.)
#
# Output layout: buildNpmPackage installs via `npm pack` to
# $out/lib/node_modules/<name from package.json> — the bare-name layout the
# dsh profile peers expect. package.json's `files` includes lib/, so the
# freshly built lib/client.js and lib/index.js are what land in the store.
{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
  nodejs,
}:

buildNpmPackage (finalAttrs: {
  pname = "dsh-client-ui-forkspace";
  version = "0.1.2-rc.1";

  src = fetchFromGitHub {
    owner = "4weaver";
    repo = "dsh-client-ui-workspace";
    rev = "b693ae4aad84c83c776946404892bb40c227cea7";
    hash = "sha256-eTZfLFuA5KuqIpdBnvzh9AeboWaT91YJCgAZxPeIMcM=";
  };

  # The committed lib/ must NOT be an input: discard it so a stale artifact
  # can never be mistaken for build output. Also drop the old dep-less vendor
  # lock so only the real build lock is visible to npm.
  postPatch = ''
    rm -rf lib/types lib/client.js lib/index.js
    rm -f vendor.package-lock.json
    cp ${./vendor/package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-ElxQPbqVxVYAe1boD+ekf3182DUSTyAN762c+QoXatE=";

  # Reaches `npm ci` AND `npm rebuild`; mandatory, see header.
  npmFlags = [ "--legacy-peer-deps" ];

  # `bundle` = `npm run build:types && tsdown --config-loader unrun`, i.e.
  # exactly the two steps in the required order.
  npmBuildScript = "bundle";

  # tsc/tsdown live in devDependencies and npm ci installs them (dev deps are
  # not omitted by default). Nothing reaches the network: npmConfigHook sets
  # npm_config_offline=true and every tarball comes from the npmDeps cache.
  # No prune: npmInstallFlags is untouched here, and pruning with the peer
  # flags absent would re-resolve the lock and try to fetch peers offline.
  dontNpmPrune = true;

  # The bundle inlines everything except five externals — react, react/jsx-runtime,
  # @deepseek-ai/cordis, dsh-client-store and dsh-client-ui-primitives — which the
  # dsh profile top-level / core already provide as shared singletons (the sibling
  # dsh-client-ui-workspace externalizes exactly the same set and ships an EMPTY
  # node_modules at 381 KiB). Those are DEV dependencies here: they exist to
  # typecheck and bundle, not to ship. Leaving them installed would put 153 MiB of
  # tsc/rolldown/lightningcss plus a nested duplicate copy of react and cordis
  # inside this package, which risks shadowing the shared instances the profile
  # relies on. So strip node_modules after buildNpmPackage has packed the output —
  # npmInstallHook has already run, and `files` in package.json ships only lib/
  # plus docs, so nothing the runtime needs is lost.
  postInstall = ''
    rm -rf $out/lib/node_modules/dsh-client-ui-forkspace/node_modules
  '';
  env.NODE_OPTIONS = "--max-old-space-size=4096";

  meta = {
    description = "dsh client UI fork: grouped sidebar browser with a fork-tree view";
    homepage = "https://github.com/4weaver/dsh-client-ui-workspace";
    license = lib.licenses.mit;
    platforms = lib.platforms.all;
  };
})
